### ISSUE TITLE
Port listening on localhost:5000 but not on ip:5000

### ISSUE THREAD

**Issue by m4ary** [inc0x0/multipot#1]
im running on raspberry Pi with pihole on it and everything is fine but i cannot access multipot from my computer on i enter 192.168.**.**:5000.

**Comment by inc0x0** [comment]
Hi,
sorry for the late response, I haven't seen the issue.
That's not an issue with multipot itself but with flask. By default it's only reachable on localhost as the development server is not designed to be very stable/secure. 

You can change that setting in `multipot/multipotapp.py` 
Set the `app.run()` to `app.run(host='0.0.0.0')` to run on your machines IP address.

**Comment by m4ary** [comment]
Thanks thats work
